/**
 * Every shape the partner app reads or writes, named once.
 *
 * Two kinds live here, and the split is deliberate:
 *
 *  1. Wire shapes the Foodishi API already serves — orders, the menu, the
 *     restaurant, the roster. Those are the OpenAPI types generated by
 *     `pnpm --filter @repo/api-client gen`, aliased rather than re-declared, so
 *     a column that changes server-side breaks the build instead of one screen.
 *
 *  2. Shapes the API has no route for yet — offers, coupons, reports, payouts,
 *     add-on groups, per-person permissions. Those are declared here in full.
 *     They are marked FIXTURE-ONLY and every one of them is a promise about
 *     what the backend will be asked for, written in the same house style as
 *     the generated ones so the swap is an implementation change and not a
 *     retyping of the app.
 *
 * Money is a decimal *string* everywhere, exactly as the API sends it. It is
 * parsed for display only, never for arithmetic the server has already done.
 */
import type { components } from "@repo/api-client";

/* ── 1. Shapes the API already serves ─────────────────────────────────── */

export type OrderStatus = components["schemas"]["OrderStatus"];
export type Order = components["schemas"]["OrderRead"];
export type OrderDetail = components["schemas"]["OrderDetail"];
export type OrderItem = components["schemas"]["OrderItemRead"];
export type OrderClock = components["schemas"]["OrderStatusRead"];
export type OrderEvent = components["schemas"]["OrderEventRead"];
export type CancelResult = components["schemas"]["CancelResult"];
export type ActorType = components["schemas"]["ActorType"];

export type MenuCategory =
  components["schemas"]["app__schemas__catalog__MenuCategoryRead"];
export type MenuItem =
  components["schemas"]["app__schemas__catalog__MenuItemRead"];
export type MenuItemCreate = components["schemas"]["MenuItemCreate"];
export type MenuItemPatch = components["schemas"]["MenuItemUpdate"];
export type SpiceLevel = components["schemas"]["SpiceLevel"];

export type RestaurantDetail = components["schemas"]["RestaurantDetail"];
export type RestaurantPolicy =
  components["schemas"]["app__schemas__catalog__RestaurantPolicyRead"];
export type Cuisine = components["schemas"]["CuisineRead"];

export type Address = components["schemas"]["AddressRead"];
export type Customer = components["schemas"]["UserRead"];

/**
 * The `image_url` PATCH /restaurants/{id} now accepts. `api.d.ts` is generated
 * and must never be hand-edited, so the one field that arrives with this
 * screen is added here and collapses back at the next `pnpm gen`.
 */
export type RestaurantPatch = components["schemas"]["RestaurantUpdate"] & {
  readonly image_url?: string | null;
};

/** The API's list envelope, for the pages this app reads. */
export interface Page<TRow> {
  readonly items: readonly TRow[];
  readonly total: number;
  readonly limit: number;
  readonly offset: number;
}

export type OrdersPage = Page<Order>;

/* ── 2. FIXTURE-ONLY: no endpoint yet ─────────────────────────────────── */

/**
 * The two roles this console draws.
 *
 * The API spells the senior one `admin`; every human in a restaurant calls it
 * the manager, and so does every label here. `services/api` maps the two words
 * at the seam — see `toApiRole` — so the vocabulary never leaks into a screen.
 */
export type StaffRole = "manager" | "staff";

/**
 * One named thing a person may do in one restaurant.
 *
 * Flat strings rather than a nested tree: a permission is checked in a dozen
 * places and stored on a membership row, and a tree would be re-flattened at
 * every one of them. The prefix is the surface, so `orders.*` reads as a group
 * without being one.
 */
export type Permission =
  | "dashboard.view"
  | "orders.view"
  | "orders.accept"
  | "orders.reject"
  | "orders.status"
  | "orders.cancel"
  | "orders.history"
  | "handover.view"
  | "handover.mark"
  | "menu.view"
  | "menu.availability"
  | "menu.edit"
  | "menu.delete"
  | "menu.categories"
  | "menu.modifiers"
  | "restaurant.view"
  | "restaurant.edit"
  | "staff.view"
  | "staff.manage"
  | "offers.view"
  | "offers.manage"
  | "reports.view"
  | "payments.view";

/** The person behind a roster row. Mirrors StaffUserRead, plus the avatar. */
export interface StaffPerson {
  readonly id: number;
  readonly name: string;
  readonly email: string;
  readonly phone: string;
  readonly avatar_url?: string | null;
}

/**
 * One membership: a person, the role they hold here, and the extra permissions
 * a manager has granted them on top of that role's own.
 *
 * `granted` is FIXTURE-ONLY. The API's `restaurant_staff` row carries the role
 * and nothing else, so `services/api` reports an empty grant list rather than
 * inventing one — which makes a staff member there exactly as capable as their
 * role, and never accidentally more.
 */
export interface StaffMember {
  readonly id: number;
  readonly user_id: number;
  readonly restaurant_id: number;
  readonly role: StaffRole;
  readonly is_active: boolean;
  readonly created_at: string;
  readonly updated_at: string;
  readonly user: StaffPerson;
  readonly granted: readonly Permission[];
}

/** One restaurant this account may act for, and what it may do there. */
export interface Membership {
  readonly id: number;
  readonly name: string;
  readonly slug: string;
  readonly city: string;
  readonly image_url: string | null;
  readonly is_active: boolean;
  readonly role: StaffRole;
  readonly granted: readonly Permission[];
}

/** The signed-in person, as this console needs them. */
export interface Profile {
  readonly id: number;
  readonly name: string;
  readonly email: string;
  readonly phone: string;
  readonly city: string;
  readonly avatar_url?: string | null;
}

/* Add-ons and variants. */

/**
 * How a group of choices behaves. `variant` is one-of and must be answered —
 * a biryani is a half or a full plate, never neither and never both. `addon`
 * is any-of and may be skipped.
 */
export type ModifierKind = "variant" | "addon";

export interface ModifierOption {
  readonly id: number;
  readonly group_id: number;
  readonly name: string;
  /** Added to the dish price. "0.00" for a choice that costs nothing. */
  readonly price_delta: string;
  readonly is_available: boolean;
  readonly sort_order: number;
}

export interface ModifierGroup {
  readonly id: number;
  readonly restaurant_id: number;
  readonly name: string;
  readonly kind: ModifierKind;
  /** How many options a customer must pick. A variant group is 1. */
  readonly min_select: number;
  /** How many they may pick. A variant group is 1. */
  readonly max_select: number;
  readonly sort_order: number;
  readonly options: readonly ModifierOption[];
  /** Dishes this group is attached to. */
  readonly menu_item_ids: readonly number[];
}

/* Offers, discounts and coupons. */

/**
 * `percent` takes a share off the subtotal, `flat` takes rupees off it, and
 * `free_delivery` waives the delivery fee. Three cases rather than a nullable
 * pair of columns, so an offer cannot be half of two kinds at once.
 */
export type OfferKind = "percent" | "flat" | "free_delivery";

export interface Offer {
  readonly id: number;
  readonly restaurant_id: number;
  readonly title: string;
  readonly description: string | null;
  readonly kind: OfferKind;
  /** Percent for `percent`, rupees for `flat`, ignored for `free_delivery`. */
  readonly value: string;
  /** No discount is ever larger than this, whatever the percentage says. */
  readonly max_discount: string | null;
  readonly min_order_value: string;
  /** Null means the offer applies to the whole menu. */
  readonly menu_item_ids: readonly number[] | null;
  readonly starts_at: string;
  readonly ends_at: string | null;
  readonly is_active: boolean;
  /** How many orders have used it. Read-only — the server counts these. */
  readonly redemption_count: number;
}

export interface Coupon {
  readonly id: number;
  readonly restaurant_id: number;
  /** Upper-case, no spaces. What the customer types at checkout. */
  readonly code: string;
  readonly kind: OfferKind;
  readonly value: string;
  readonly max_discount: string | null;
  readonly min_order_value: string;
  /** Null means unlimited. */
  readonly usage_limit: number | null;
  /** How many times one customer may use it. */
  readonly per_user_limit: number;
  readonly starts_at: string;
  readonly ends_at: string | null;
  readonly is_active: boolean;
  readonly redemption_count: number;
}

export type OfferCreate = Omit<
  Offer,
  "id" | "restaurant_id" | "redemption_count"
>;
export type OfferPatch = Partial<OfferCreate>;
export type CouponCreate = Omit<
  Coupon,
  "id" | "restaurant_id" | "redemption_count"
>;
export type CouponPatch = Partial<CouponCreate>;

/* Reports. */

/** One day of trade. `date` is a local calendar day, "2026-08-21". */
export interface SalesDay {
  readonly date: string;
  readonly orders: number;
  readonly delivered: number;
  readonly cancelled: number;
  /** Delivered orders only. Cancelled trade is not revenue. */
  readonly revenue: string;
  readonly discount: string;
}

export interface PopularItem {
  readonly menu_item_id: number;
  readonly name: string;
  /**
   * Null for a dish deleted since it sold. The name still resolves — order
   * lines freeze it — but there is no live row to read a category off, and
   * inventing one would file the dish under a category it never belonged to.
   */
  readonly category_name: string | null;
  readonly quantity: number;
  readonly orders: number;
  readonly revenue: string;
  /** Null for the same reason: a deleted dish is neither available nor not. */
  readonly is_available: boolean | null;
}

/** How well the kitchen kept its promises over the window. */
export interface PerformanceReport {
  readonly orders: number;
  readonly delivered: number;
  readonly cancelled: number;
  readonly rejected: number;
  /** Delivered on or before the promised time, as a share of delivered. */
  readonly on_time_rate: number;
  /** Whole minutes, averaged over delivered orders. */
  readonly avg_prep_minutes: number;
  /** Placed to delivered, whole minutes. */
  readonly avg_delivery_minutes: number;
  readonly avg_order_value: string;
  readonly rating: string;
  readonly rating_count: number;
}

export interface ReportWindow {
  /** Inclusive local calendar day. */
  readonly from: string;
  /** Inclusive local calendar day. */
  readonly to: string;
}

/* Payments. */

/** What the restaurant earned over a window, and what was taken off it. */
export interface EarningsSummary {
  readonly gross: string;
  readonly commission: string;
  readonly commission_percent: string;
  readonly tax_on_commission: string;
  readonly refunds: string;
  readonly net: string;
  readonly settled: string;
  readonly pending: string;
}

// ALIASED, not re-declared. The hand-written union had THREE members and the
// generated schema has four: `failed` was missing -- a bank rejection, the one
// settlement status a restaurant most needs to see. Both display maps in
// app/payments/page.tsx are exhaustive over this union, so with `failed` absent
// they had no entry for it, the badge would render empty and untoned, and the
// restaurant would reasonably read a failed payout as fine. `tsc` could not see
// it because the value is cast at the boundary in fetcher.ts.
export type SettlementStatus =
  components["schemas"]["SettlementStatus"];

export interface Settlement {
  readonly id: number;
  readonly restaurant_id: number;
  readonly reference: string;
  readonly period_from: string;
  readonly period_to: string;
  readonly orders_count: number;
  readonly gross: string;
  readonly commission: string;
  /**
   * GST on the commission, broken out rather than folded into it. A partner
   * reconciling a statement has to be able to see the two separately — one is
   * the platform's fee and the other is tax on that fee.
   */
  readonly tax_on_commission: string;
  readonly refunds: string;
  readonly net: string;
  readonly status: SettlementStatus;
  /** When it lands, or landed. */
  readonly paid_at: string | null;
  /**
   * The bank account's last four digits, and nothing more of it. Null before a
   * destination has been recorded — a scheduled statement has no account yet.
   */
  readonly account_last4: string | null;
}

export type LedgerKind = "order" | "commission" | "refund" | "payout";

/** One line of the money trail, newest first. */
export interface LedgerEntry {
  /**
   * "<kind>:<source row id>", e.g. "commission:412".
   *
   * A bare integer could not be unique: a delivered order produces both an
   * `order` line and a `commission` line from the same order id, so any client
   * keying a list by id would drop one of them.
   */
  readonly id: string;
  readonly restaurant_id: number;
  readonly kind: LedgerKind;
  readonly occurred_at: string;
  readonly order_id: number | null;
  readonly settlement_id: number | null;
  readonly description: string;
  /** Signed: what it did to the restaurant's balance. */
  readonly amount: string;
}

/* ── Joining Foodishi ─────────────────────────────────────────────────── */

/**
 * Where a request to join has got to. Terminal in two of the three states.
 *
 * Declared by hand rather than aliased from `components["schemas"]`, and only
 * because the generated types are a snapshot: the routes exist
 * (POST /restaurant-applications and the /admin queue behind it), but
 * `packages/api-client/src/types/api.d.ts` is regenerated from a RUNNING API
 * with `pnpm --filter @repo/api-client gen`. Until somebody runs that against
 * an API carrying these routes, aliasing them would not compile.
 *
 * Replace all three declarations below with the aliases once it has been run —
 * same treatment `MyProfile` in @repo/api-client documents for `platform_role`.
 */
export type ApplicationStatus = "pending" | "approved" | "rejected";

/** One application to put a restaurant on Foodishi, as its applicant sees it. */
export interface RestaurantApplication {
  readonly id: number;
  readonly status: ApplicationStatus;

  readonly name: string;
  readonly slug: string;
  readonly description: string | null;
  readonly city: string;
  readonly area: string;
  readonly address_line: string;
  readonly latitude: string;
  readonly longitude: string;
  readonly phone: string;
  readonly price_for_two: string;
  readonly avg_prep_minutes: number;
  readonly opens_at: string;
  readonly closes_at: string;
  readonly note: string | null;

  /**
   * Why, in the operator's own words. Written for the applicant to read, so it
   * is rendered verbatim and never summarised — on a rejection it is the only
   * thing that tells them what to change.
   */
  readonly decision_note: string | null;
  readonly reviewed_at: string | null;
  /**
   * The restaurant an approval created. Non-null is the applicant's signal that
   * their console has something in it — and that the kitchen is theirs to open,
   * because approval creates it dormant.
   */
  readonly restaurant_id: number | null;
  readonly created_at: string;
  readonly updated_at: string;
}

/**
 * What an applicant sends. Every field the `restaurants` table requires, which
 * is why an approval needs nothing further from anybody.
 *
 * `is_active` is absent on purpose and is not an omission to fix later: whether
 * a kitchen takes orders is not a description of it, and an applicant does not
 * get to declare it. Approval creates the restaurant closed.
 */
export interface ApplicationSubmit {
  readonly name: string;
  readonly slug: string;
  readonly description?: string | null;
  readonly city: string;
  readonly area: string;
  readonly address_line: string;
  readonly latitude: string;
  readonly longitude: string;
  readonly phone: string;
  readonly price_for_two: string;
  readonly avg_prep_minutes: number;
  readonly opens_at: string;
  readonly closes_at: string;
  readonly note?: string | null;
}
