/**
 * @repo/api-client — the only way the three apps talk to the Foodishi API.
 * No component calls fetch() directly.
 */

export { getApiBaseUrl } from "./config";

export {
  ApiError,
  extractDetail,
  isApiError,
  isNotFound,
  isRetryable,
  isUnsupported,
  requiresProfileLink,
  requiresSignIn,
  toUserMessage,
  type ApiErrorAction,
  type ValidationIssue,
} from "./error";

export {
  api,
  apiFetch,
  type QueryParams,
  type QueryValue,
  type RequestOptions,
} from "./fetcher";

export {
  ApiProvider,
  createQueryClient,
  type ApiProviderProps,
} from "./query-provider";

/** Real authentication: Supabase sign-in, the bearer token, and the /me profile. */
export {
  getSupabaseClient,
  getSupabaseConfig,
  isSupabaseConfigured,
  type SupabaseClient,
  type SupabaseConfig,
} from "./auth/client";

export {
  AuthError,
  getAccessToken,
  getAuthUser,
  getSession,
  isAuthError,
  onAuthChange,
  signIn,
  signOut,
  signUp,
  type AuthChangeEvent,
  type AuthChangeHandler,
  type Session,
  type SignUpResult,
  type User,
} from "./auth/session";

export {
  fetchMyProfile,
  type MyProfile,
  fetchMyRestaurants,
  linkProfile,
  type MyRestaurant,
  type ProfileLinkPayload,
  type UserProfile,
} from "./auth/profile";

export {
  SessionProvider,
  useSession,
  type ProfileStatus,
  type SessionContextValue,
  type SessionProviderProps,
  type SessionStatus,
} from "./auth/provider";

export {
  AuthSpinner,
  RequireAuth,
  type AuthSpinnerProps,
  type RequireAuthProps,
} from "./auth/require";

/**
 * @deprecated PHASE-1 DEV IDENTITY — NOT AUTHENTICATION, and no longer accepted
 * by the API. AUTH_ENABLED is on and every protected endpoint 401s on the old
 * `X-Dev-User-Id` header; the fetcher strips it. Kept only so the three apps
 * still compile while their call sites move to `SessionProvider`/`useSession`.
 * Delete this block once nothing imports it.
 */
export {
  clearIdentity,
  getIdentity,
  getRestaurantId,
  getUserId,
  requireRestaurantId,
  requireUserId,
  setRestaurantId,
  setUserId,
  subscribeToIdentity,
  type DevIdentity,
} from "./identity";

/** Generated from the live FastAPI schema — run `pnpm --filter @repo/api-client gen`. */
export type { components, operations, paths } from "./types/api";

// Seeded development logins, rendered by the /creds page in each console.
// GENERATED by `foodishi-api: uv run python -m app.seed.dev_credentials`.
export {
  DEV_CREDENTIALS,
  DEV_PASSWORD,
  type DevCredential,
} from "./dev-credentials";
